"""empty message

Revision ID: 2cdc767019b4
Revises: 
Create Date: 2024-08-31 00:40:19.538011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cdc767019b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('appointments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('Admin', 'User', name='role_type'), nullable=True))
        batch_op.add_column(sa.Column('account_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('OTP', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('OTP_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('additional_info')
        batch_op.drop_column('OTP_expiry')
        batch_op.drop_column('OTP')
        batch_op.drop_column('account_verified')
        batch_op.drop_column('role')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointments_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
