"""Photo url field

Revision ID: 300538b757f1
Revises: 34a5c01eb1a5
Create Date: 2024-09-09 03:10:34.603002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300538b757f1'
down_revision = '34a5c01eb1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
