"""Added role on user

Revision ID: 5a9762bb94b1
Revises: 2cdc767019b4
Create Date: 2024-09-06 21:52:31.771401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a9762bb94b1'
down_revision = '2cdc767019b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('amount_payable',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_constraint('appointments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('ADMIN', 'USER', name='role_type'), nullable=True))
        batch_op.add_column(sa.Column('account_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('OTP', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('OTP_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('additional_info')
        batch_op.drop_column('OTP_expiry')
        batch_op.drop_column('OTP')
        batch_op.drop_column('account_verified')
        batch_op.drop_column('role')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointments_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('amount_payable',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
