"""bookings and amount_earned

Revision ID: 89104f8d3928
Revises: a1b006d32364
Create Date: 2024-09-07 20:00:31.620898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89104f8d3928'
down_revision = 'a1b006d32364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_earned', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('bookings', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True))
        batch_op.drop_column('additional_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('bookings')
        batch_op.drop_column('amount_earned')

    # ### end Alembic commands ###
