"""Added workingdays

Revision ID: a1b006d32364
Revises: da681b227442
Create Date: 2024-09-07 16:41:43.592460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b006d32364'
down_revision = 'da681b227442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_days', postgresql.ARRAY(sa.String(length=100)), nullable=False))
        batch_op.drop_column('available_dates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_dates', postgresql.ARRAY(sa.DATE()), autoincrement=False, nullable=True))
        batch_op.drop_column('working_days')

    # ### end Alembic commands ###
