"""added image fields to appointment

Revision ID: aaa48cb4a897
Revises: 300538b757f1
Create Date: 2024-09-09 04:34:47.977282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aaa48cb4a897'
down_revision = '300538b757f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('supporting_images', postgresql.ARRAY(sa.Text()), nullable=True))
        batch_op.alter_column('working_days',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               type_=postgresql.ARRAY(sa.String(length=28)),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('working_days',
               existing_type=postgresql.ARRAY(sa.String(length=28)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=100)),
               existing_nullable=False)
        batch_op.drop_column('supporting_images')
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
