"""tweak amount_earned

Revision ID: c227d818156c
Revises: 89104f8d3928
Create Date: 2024-09-07 21:00:39.745769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c227d818156c'
down_revision = '89104f8d3928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('amount_earned',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('amount_earned',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
