"""changed enum field

Revision ID: e958c5b8aece
Revises: d4f30fbe84df
Create Date: 2024-09-07 11:04:11.471944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e958c5b8aece'
down_revision = 'd4f30fbe84df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('Admin', 'User', name='role_type'),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=15),
               type_=postgresql.ENUM('Admin', 'User', name='role_type'),
               existing_nullable=True)

    # ### end Alembic commands ###
